#!/usr/bin/env bash
# Generated by Automation/package-chapter09.py.
set -euo pipefail
signal47_repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
signal47_release="$signal47_repo_dir/Artifacts/Releases/Chapter09-86a28b30ad94/Start-SIGNAL47.sh"
if [[ ! -x "$signal47_release" ]]; then
  printf '%s\n' 'Den bestemte SIGNAL / 47-pakken mangler eller kan ikke kjøres:' "$signal47_release" >&2
  exit 1
fi
exec "$signal47_release" "$@"
