# Full prologue through the real interactables and console DOM.
# The render loop is held and the game is advanced with S47.tick(), so it runs
# in a software renderer too. Usage: python3 tools/walkthrough.py OUTDIR WxH quality
# Set S47_URL to test another build, for example the Pages build served over HTTP.
import asyncio, math, sys, json, time, os
from playwright.async_api import async_playwright
OUT = sys.argv[1]; W, H = (int(v) for v in sys.argv[2].split('x')); Q = sys.argv[3] if len(sys.argv) > 3 else 'high'
URL = os.environ.get('S47_URL') or 'file://' + os.path.abspath('dist-single/index.html')
checks = []
def check(ok, what): checks.append(('PASS' if ok else 'FAIL', what)); print(('PASS ' if ok else 'FAIL ') + what, flush=True)

async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(args=['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required'])
        pg = await b.new_page(viewport={'width': W, 'height': H}); pg.set_default_timeout(240000)
        errs = []
        pg.on('console', lambda m: errs.append(f'{m.type}: {m.text}') if m.type in ('error', 'warning') else None)
        pg.on('pageerror', lambda e: errs.append('PAGEERROR: ' + str(e)))
        # Headless Chromium stalls screenshots while the pointer is locked, so tests skip the lock.
        await pg.add_init_script("HTMLElement.prototype.requestPointerLock = function(){ return Promise.resolve(); };")
        await pg.goto(URL)
        await pg.wait_for_selector('button[data-a=start]')
        await pg.evaluate(f"S47.setQuality('{Q}')")
        await pg.wait_for_timeout(2500)
        await pg.screenshot(path=f'{OUT}/00_title.png')
        await pg.click('button[data-a=start]')            # real click, proves the fade layer no longer blocks
        await pg.wait_for_timeout(300)
        await pg.evaluate("S47.hold = true")
        ev = lambda js: pg.evaluate(js)
        async def tick(s): await ev(f"S47.tick({s})")
        async def shot(name): await pg.screenshot(path=f'{OUT}/{name}.png')
        async def look(x, z, yaw, pitch=0.0): await ev(f"S47.player.place({x},{z},{yaw}); S47.player.pitch={pitch};")
        use = lambda i: ev(f"S47.game.d.inter.get('{i}').use()")
        label = lambda i: ev(f"S47.game.d.inter.get('{i}').label()")
        await tick(2.0); await shot('01_spawn')
        check(await ev("S47.game.phase") == 'intro', 'game starts in intro phase')
        # the picture and the sounds (core/vhs.ts, core/Audio.ts)
        check(await ev("S47.vhs.picture") == ('vhs' if Q == 'high' else 'off') and await ev("S47.vhs.on") == (Q == 'high'), f'picture defaults to {"the VHS look" if Q == "high" else "clean"} on {Q}')
        check(await ev("S47.renderer.info.render.calls") > 60, f'draw calls counted over both passes ({await ev("S47.renderer.info.render.calls")})')
        try: await pg.wait_for_function("Object.keys(S47.game.d.audio.buf).length >= 25", timeout=60000)
        except Exception: pass
        check(await ev("Object.keys(S47.game.d.audio.buf).length") == 25, 'all 25 sounds decoded')
        check(await ev("(()=>{ const a=S47.game.d.audio; ['tile','concrete','dirt','wood','carpet'].forEach(s=>a.step(s)); a.thunder(0.4); a.far('owl', S47.player.pos, 0.3); return true; })()"), 'steps on every surface, far thunder and a far owl play')
        dup = await ev("(()=>{ const ids = S47.game.d.inter.items.map(i => i.id); return ids.filter((x, i) => ids.indexOf(x) !== i); })()")
        check(not dup, f'every interactable has its own id ({dup})')
        await use('logbook'); await tick(0.2); await shot('02_shiftlog')
        await ev("S47.game.d.ui.close()"); await tick(1)
        check(await ev("S47.game.logRead") is True, 'shift log read and filed')
        await use('coffeePot'); await tick(2)
        check(await ev("S47.game.coffee") == 'poured', 'coffee poured')
        await use('rack'); await tick(2.5)
        check(await ev("S47.game.powered") is True, 'RX bank 3 powered')
        # Night Shift's papers and the operations terminal (KAPITLER.md)
        for i, did in (('excBinder', 'binder'), ('serviceRecord', 'service'), ('telex', 'telex'), ('rfiCard', 'rfiCard'), ('halley', 'halley')):
            await use(i); await tick(0.1)
            if i == 'excBinder': await shot('02b_binder')
            await ev("S47.game.d.ui.close()"); await tick(0.1)
        papers = await ev("S47.game.docs.map(d => d.id)")
        check(all(x in papers for x in ('binder', 'service', 'telex', 'rfiCard', 'halley')), f'binder, service record, telex, card and poster are read and filed ({papers})')
        check(await ev("document.querySelector('.page .pencil') === null"), 'no paper left open')
        await use('excBinder'); await tick(0.1)
        check(await ev("[...document.querySelectorAll('.page .pencil')].some(e => e.textContent.includes('keep doing it'))"), 'the pencil in the binder is drawn by hand')
        # round 10 (Codex): the sheets lie on fanfold, the last one on the old paper of 1947
        sheets = await ev("""(async()=>{ const s=[...document.querySelectorAll('.sheets .page.sheet')];
          await Promise.all(s.map(e => new Promise(r => { const i = new Image(); i.onload = () => r(true); i.onerror = () => r(false); i.src = getComputedStyle(e).backgroundImage.slice(5, -2); })));
          const ok = await Promise.all(s.map(e => new Promise(r => { const i = new Image(); i.onload = () => r(i.naturalWidth); i.onerror = () => r(0); i.src = getComputedStyle(e).backgroundImage.slice(5, -2); })));
          return { n: s.length, widths: ok, last: s.length ? s[s.length - 1].textContent : '', old: s.length > 2 && getComputedStyle(s[2]).backgroundImage !== getComputedStyle(s[0]).backgroundImage }; })()""")
        check(sheets['n'] == 3 and all(w == 1024 for w in sheets['widths']) and '07/--/47' in sheets['last'] and sheets['old'],
              f"the binder's three sheets on fanfold paper, the 1947 sheet on the old paper ({sheets['n']}, {sheets['widths']})")
        await shot('02c_binder_sheets')
        await ev("S47.game.d.ui.close()"); await tick(0.1)
        await pg.wait_for_function("S47.art().loaded.includes('halleyPoster')", timeout=60000)
        poster = await ev("(()=>{ let t = null; S47.room.objs.halley.traverse(o => { if (o.material && o.material.map && o.material.map.userData) t = o.material.map; }); return !!t && t.userData.fromArt === true; })()")
        check(poster, "the Halley poster on the wall is Codex's picture with the words drawn on it")
        await use('halley'); await tick(0.2); await shot('02d_halley_poster')
        await ev("S47.game.d.ui.close()"); await tick(0.1)
        await use('opsTerminal'); await tick(0.1)
        async def term(c):
            await pg.click(f'.term-cmds button[data-c="{c}"]'); await tick(0.05)
            return await ev("document.querySelector('.term-out').textContent")
        out = await term('DIR SURVEY.RAW')
        check('RUN860413_2341.DAT' in out and 'Total of 3 files' in out and '0529' not in out, 'the terminal lists tonight\'s survey files')
        out = await term('SHOW TAPES')
        check('001-046, 048-1311' in out, 'the tape catalogue skips reel 047')
        out = await term('SHOW TAPES 040-050')
        check('046   09-AUG-79' in out and '048   11-AUG-79' in out and '\n047 ' not in out, 'reels 046 and 048 are there, 047 is not')
        out = await term('SHOW EXCEPTIONS')
        check('-38 LY' in out and '3 entries' in out, 'three earlier negative ranges in the exceptions')
        await pg.fill('.term-line input', 'show log'); await pg.press('.term-line input', 'Enter'); await tick(0.05)
        out = await ev("document.querySelector('.term-out').textContent")
        check('23:14' in out and out.count('K3 CLOSED') == 1 and 'SURVEY RUN OPENED' in out, 'typed SHOW LOG: the evening trip and the bank switched back on')
        check(await ev("S47.game.d.ui.modal && S47.game.d.ui.modal.classList.contains('termview')"), 'typing in the terminal does not close it (the game keys stay out)')
        await shot('02c_terminal')
        await pg.click('.term-foot [data-a=close]'); await tick(0.1)
        await use('radio'); await tick(0.5)
        check(await ev("S47.game.radioOn") is True, 'the radio plays')
        await look(0.05, -1.7, 0, -0.32); await tick(0.2); await shot('03_crts_on')
        await use('crtCenter'); await tick(0.3); await shot('04_console_cal')
        async def setrx(f, g, bw, az):
            await ev(f"""(()=>{{const set=(k,v)=>{{const i=document.querySelector('input[data-k='+k+']'); i.value=v; i.dispatchEvent(new Event('input'))}};
              set('frequency',{f}); set('gain',{g}); set('bandwidth',{bw}); set('azimuth',{az});}})()""")
        # wrong values first: must not pass
        await setrx(1419.7, 30, 80, 20); await pg.click('[data-a=act]')
        check(await ev("S47.game.rx.stage") == 0, 'wrong calibration is rejected')
        await setrx(1419.900, 55, 48, 42); await pg.click('[data-a=act]')
        check(await ev("S47.game.rx.stage") == 1, 'calibration 1419.900 accepted')
        await setrx(1420.110, 55, 15, 42); await pg.click('[data-a=act]')
        check(await ev("S47.game.rx.stage") == 2, 'interference 1420.110 notched')
        await tick(0.2); await shot('05_console_survey')
        await pg.click('[data-a=exit]'); await tick(12)
        await tick(4)
        check(await ev("S47.game.phase") == 'residual', 'time skip lands at 02:13 residual')
        await tick(7)
        check(await ev("S47.game.rxc.residualVisible") is True, 'residual appears on the spectrum')
        await use('crtCenter'); await tick(0.2)
        # the signal comes through as the receiver closes on 1420.405 (core/signalVoice.ts)
        await setrx(1420.30, 90, 10, 83); await tick(0.5)
        off = await ev("S47.game.d.audio.signal ? S47.game.d.audio.signal.level : 0")
        await setrx(1420.405, 90, 10, 83); await tick(0.5); await shot('06_console_residual')
        on = await ev("S47.game.d.audio.signal ? S47.game.d.audio.signal.level : 0")
        check(on > 0.8 and on - off > 0.4, f'the signal gets clearer as the receiver closes on 1420.405 ({off:.2f} off the peak, {on:.2f} on it)')
        await pg.click('[data-a=act]')
        check(await ev("S47.game.rx.stage") == 3 and await ev("S47.game.phase") == 'locked', 'pattern 4/7 locked at 1420.405')
        await tick(1.5); await shot('07_console_locked')
        await pg.click('[data-a=exit]'); await tick(0.5)
        # the signal processor has the tape now: play it harmonized, then stop
        await use('decoder'); await tick(0.2)
        check(await ev("!!document.querySelector('.dsp-scope')"), 'the signal processor opens with the tape')
        await pg.click('.labpanel [data-a=play]'); await tick(0.6)
        check(await ev("S47.game.decoder.playing"), 'the tape plays harmonized from the rack')
        await pg.wait_for_timeout(1500); await tick(0.5); await shot('07b_signal_processor')
        await pg.click('.labpanel [data-a=play]'); await tick(0.2)
        check(not await ev("S47.game.decoder.playing"), 'and stops')
        await ev("S47.game.d.ui.close()"); await tick(0.2)
        # the doors are free, even in the prologue: open the service door and shut it again
        await look(4.5, 1.6, -math.pi / 2, 0.0); await tick(0.1)
        check(await ev("document.querySelector('.crosshair').classList.contains('active') && getComputedStyle(document.querySelector('.crosshair')).backgroundImage.includes('svg')"),
              'a hand instead of the dot on something that can be used')
        await use('doorEast'); await tick(1.2)
        check(await ev("S47.doors.isOpen('east') && S47.yard.zone.eastDoor.enabled"), 'the service door opens in the prologue')
        await use('doorEast'); await tick(1.2)
        check(await ev("!S47.doors.isOpen('east') && !S47.yard.zone.eastDoor.enabled"), 'and shuts again')
        await use('crtRight'); await tick(5)
        check(await ev("S47.game.phase") == 'printing', 'direction solve starts printer')
        await tick(6)
        check(await ev("S47.game.phase") == 'printed', 'printout ready')
        await use('printer'); await tick(0.2); await shot('08_printout')
        await ev("S47.game.d.ui.close()"); await tick(3.5)
        check(await ev("S47.game.ringing") is True, 'phone rings after printout')
        await use('phone'); await tick(6)
        check(await ev("S47.game.phase") == 'countdown', 'call ends, 47 s countdown runs')
        await look(2.4, 1.6, 3.14159, -0.35); await tick(0.2); await shot('09_mug_before')
        since = await ev("S47.game.gt - S47.game.lineDeadT")
        await tick(39.6 - since)
        check(not await ev("S47.game.ns.k3Open"), 'bank 3 still on at 39.6 s')
        await tick(0.8)
        check(await ev("S47.game.ns.k3Open") and await ev("S47.game.phase") == 'countdown', 'relay K3 trips at 40 s, seven seconds before the impact')
        check(await ev("S47.room.lever.rotation.z") < 0 and not await ev("S47.room.crtCenter.powered"), 'the lever drops and the spectrum screen goes dark')
        await tick(46.6 - 40.4)
        check(await ev("S47.game.phase") == 'countdown', 'nothing happens before 47 s (t=%.1f)' % await ev("S47.game.gt - S47.game.lineDeadT"))
        await tick(0.6)
        check(await ev("S47.game.phase") == 'event', 'impact at 47 s (t=%.1f)' % await ev("S47.game.gt - S47.game.lineDeadT"))
        await tick(1.8); await shot('10_mug_broken')
        check(await ev("S47.room.mug.visible") is False, 'mug shattered')
        lines = await ev("S47.game.ns.log.map(l => l[1])")
        check(any('WWVB REFERENCE LOST' in l for l in lines) and any('HOLDOVER 00:00:47' in l for l in lines) and any('K3 OPEN' in l for l in lines), 'the console log has the clock lost, K3 open and 47 s of holdover')
        await tick(1.4)
        check(await ev("S47.game.phase") == 'turning', 'dishes start turning')
        await tick(1.5)
        await look(0.05, -2.2, 0, 0.08); await tick(0.1); await shot('11_dishes_turning')
        for i in range(30):
            await tick(1)
            if await ev("S47.game.phase") in ('end',): break
        check(await ev("S47.game.phase") == 'end', 'all dishes arrived')
        az = await ev("S47.ext.dishes.map(d=>Math.round(d.curAz))")
        check(all(a == 26 for a in az), f'all {len(az)} dishes at az 026')
        # No end card any more: the night goes on. A chapter card on the black closes the
        # prologue and names chapter one, then the yard door is open behind it.
        for i in range(20):
            await tick(0.5)
            if await ev("!!document.querySelector('.chapter-card')"): break
        check(await ev("!!document.querySelector('.chapter-card')"), 'chapter card after the prologue')
        text = await ev("document.querySelector('.chapter-card').textContent")
        check('NIGHT SHIFT' in text and 'CHAPTER ONE' in text and 'THE SECOND EXPOSURE' in text, 'chapter card closes the prologue and names chapter one')
        check(await pg.locator('.endcard').count() == 0, 'no end card between the prologue and chapter one')
        await pg.wait_for_function("() => { const b = document.querySelector('.chapter-card .cc-b'); return !!b && getComputedStyle(b).opacity === '1'; }", polling=500)
        await shot('12_chapter_card')
        await tick(7)
        check(await ev("!document.querySelector('.chapter-card:not(.out)')") and await ev("S47.game.phase") == 'ch1' and not await ev("S47.game.cinematic"), 'chapter one begins behind the card')
        check(await ev("S47.game.ns.k3Open") and await label('rack') == 'Reset RX bank 3', 'bank 3 is still out in chapter one')
        await use('rack'); await tick(1)
        check(not await ev("S47.game.ns.k3Open") and await ev("S47.room.crtCenter.powered"), 'and comes back with the lever')
        check(await ev("S47.sky.comet.visible"), "Halley's comet is up in the south at 02:16")
        await look(7.5, 1.6, -math.pi / 2, 0.0); await tick(0.2)
        check(await ev("S47.game.ns.jacket") and not await ev("S47.room.objs.jacket.visible"), 'the jacket comes along the first time out')
        # the new chapter is an autosave of this case, with a picture and the chapter's name
        await pg.wait_for_function("S47.saves.list(S47.caseId()).some(m => m.chapter.startsWith('Chapter 1'))", polling=300, timeout=20000)
        m = await ev("S47.saves.list(S47.caseId())[0]")
        check(m['kind'] == 'auto' and m['chapter'] == 'Chapter 1: The Second Exposure' and (m['thumb'] or '').startswith('data:image/jpeg'), f"autosave at chapter one: {m['id']}, {m['place']}, {m['clock']}")
        print('\n'.join(errs[:30]) or 'no console errors/warnings')
        if errs: check(False, 'console clean')
        json.dump(checks, open(f'{OUT}/checks.json', 'w'), indent=1)
        fails = [c for c in checks if c[0] == 'FAIL']
        print(f'{len(checks) - len(fails)} of {len(checks)} PASS')
        await b.close()
        if fails: raise SystemExit(1)
asyncio.run(main())
