#!/usr/bin/env python3
"""Package the matching Chapter09 Linux build; never build or launch the game."""
import argparse
import gzip
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import stat
import sys
import tarfile
import tempfile

ROOT = Path(__file__).resolve().parents[1]
BUILD_METADATA = {"build-manifest.json", "build-id.txt"}
PACKAGE_MANIFEST = "package-manifest.json"
GENERATED_MARKER = "# Generated by Automation/package-chapter09.py."
CHUNK = 1024 * 1024


def require(condition, message):
    if not condition:
        raise ValueError(message)


def file_hash(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(CHUNK), b""):
            digest.update(chunk)
    return digest.hexdigest()


def tree_hash(paths, relative_to):
    """Match stamp-gauntlet-build.py: sorted relative path, NUL, file bytes."""
    digest = hashlib.sha256()
    for path in paths:
        if not path.is_file():
            continue
        digest.update(path.relative_to(relative_to).as_posix().encode("utf-8") + b"\0")
        with path.open("rb") as stream:
            for chunk in iter(lambda: stream.read(CHUNK), b""):
                digest.update(chunk)
    return digest.hexdigest()


def source_hash(root):
    # Preserve the exact base ordering used by the build-stamping script.
    bases = ("Unity/Assets", "Unity/Packages", "Unity/ProjectSettings")
    for base in bases:
        require((root / base).is_dir(), f"Missing source directory: {base}")
    return tree_hash((p for base in bases for p in sorted((root / base).rglob("*"))), root)


def regular_tree(root):
    require(root.is_dir() and not root.is_symlink(), f"Not a regular build/package directory: {root}")
    paths = sorted(root.rglob("*"))
    for path in paths:
        require(not path.is_symlink(), f"Symbolic links are not supported in this release: {path}")
        require(path.is_file() or path.is_dir(), f"Unsupported special file: {path}")
    return paths


def build_payload_hash(build):
    return tree_hash((p for p in regular_tree(build) if p.name not in BUILD_METADATA), build)


def verify_build(root, build, expected_source=None):
    regular_tree(build)
    manifest = json.loads((build / "build-manifest.json").read_text(encoding="utf-8"))
    for name in ("unity_source_sha256", "player_sha256", "build_payload_sha256"):
        require(isinstance(manifest.get(name), str) and re.fullmatch(r"[0-9a-f]{64}", manifest[name]),
                f"Invalid build-manifest field: {name}")
    require(isinstance(manifest.get("base_revision"), str) and re.fullmatch(r"[0-9a-f]{40}", manifest["base_revision"]),
            "Build manifest needs an exact Git revision.")
    require(isinstance(manifest.get("working_tree_changes"), bool), "Build manifest needs its working-tree status.")
    if expected_source:
        require(manifest["unity_source_sha256"] == expected_source, "Build differs from --expect-source; nothing packaged.")
    require(source_hash(root) == manifest["unity_source_sha256"],
            "Current Unity source differs from the tested build-manifest; rebuild and reverify before packaging.")
    for name in ("Signal47.x86_64", "UnityPlayer.so", "Signal47_Data/boot.config", "THIRD_PARTY_NOTICES.md", "VT323-OFL.txt"):
        require((build / name).is_file(), f"Missing runtime or license file: {name}")
    require((build / "Signal47.x86_64").stat().st_mode & 0o111, "The native player is not executable.")
    require(file_hash(build / "Signal47.x86_64") == manifest["player_sha256"], "Native player differs from build-manifest.")
    require(build_payload_hash(build) == manifest["build_payload_sha256"], "Build payload differs from build-manifest.")
    state = "working-tree" if manifest["working_tree_changes"] else "clean"
    expected_id = f"{manifest['base_revision']} {state} source-sha256:{manifest['unity_source_sha256']}"
    require((build / "build-id.txt").read_text(encoding="utf-8").strip() == expected_id,
            "build-id.txt does not match build-manifest.json.")
    return manifest


def package_launcher():
    return """#!/usr/bin/env bash
set -euo pipefail
signal47_release_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
cd -- "$signal47_release_dir"
# Respect an explicitly configured audio server; repair absent desktop socket env only.
if [[ -z "${PULSE_SERVER:-}" ]]; then
  for signal47_runtime_dir in "${XDG_RUNTIME_DIR:-}" "/run/user/$(id -u)"; do
    if [[ -n "$signal47_runtime_dir" && -S "$signal47_runtime_dir/pulse/native" ]]; then
      export XDG_RUNTIME_DIR="$signal47_runtime_dir"
      export PULSE_SERVER="unix:$signal47_runtime_dir/pulse/native"
      break
    fi
  done
fi
exec "./Signal47.x86_64" "$@"
"""


def repository_launcher(package_id):
    return f"""#!/usr/bin/env bash
{GENERATED_MARKER}
set -euo pipefail
signal47_repo_dir="$(cd -- "$(dirname -- "${{BASH_SOURCE[0]}}")" && pwd -P)"
signal47_release="$signal47_repo_dir/Artifacts/Releases/{package_id}/Start-SIGNAL47.sh"
if [[ ! -x "$signal47_release" ]]; then
  printf '%s\\n' 'Den bestemte SIGNAL / 47-pakken mangler eller kan ikke kjøres:' "$signal47_release" >&2
  exit 1
fi
exec "$signal47_release" "$@"
"""


def start_text(package_id, build, candidate=False):
    if package_id.startswith("Archive16-"):
        return f"""SIGNAL / 47 — ARCHIVE16 / SELVSTENDIG PRODUKSJONSPRØVE
Pakke: {package_id}
Unity-kilder SHA-256: {build['unity_source_sha256']}
Dette er en egen P04-prøve, ikke hovedspillet eller et ferdig nytt kapittel.
Start i denne mappen: ./Start-SIGNAL47.sh
Hele pakken må følge med. Progresjon lagres ikke; hovedspillets saker berøres ikke.
Klikk saksmappen eller trykk E fra bordvisningen. Tab bytter rom-/bordvisning.
1/2 åpner protokollene; 3 åpner sammenligningen etter at begge er lest.
Velg en begrunnet slutning. Escape lukker dokumentet eller åpner pause.
Native input, ytelse og blind forståelsestest er fortsatt uverifisert.
Se THIRD_PARTY_NOTICES.md og VT323-OFL.txt for kreditering.
"""
    status = 'TESTKANDIDAT: full spillerreise og ny ytelseskontroll er ikke godkjent ennå.\n' if candidate else ''
    return f"""SIGNAL / 47 — DEN ANDRE EKSPONERINGEN

Pakke: {package_id}
Kildeversjon: {build['base_revision']}
Unity-kilder SHA-256: {build['unity_source_sha256']}
{status}

START PÅ LINUX
Åpne en terminal i denne utpakkede mappen og kjør:
  ./Start-SIGNAL47.sh

Startfilen finner spillet i sin egen mappe. Hele mappen kan flyttes samlet.
Arkivet bevarer kjørerettighetene. Dersom et annet kopieringsverktøy fjernet dem:
  chmod +x Start-SIGNAL47.sh Signal47.x86_64

Velg START NIGHT SHIFT for en ny sak eller CONTINUE CHECKPOINT for å fortsette.
Lagring blir tilgjengelig etter telefonhendelsen og antennebevegelsen.
Nytt spill nullstiller den aktive saken og bevarer eksporterte fotografier.

KONTROLLER
WASD: bevegelse. Mus: se rundt. E: bruk eller undersøk.
Tab: notatbok. Escape: lukk panel eller pause.
C: kamerasøker. Space: eksponer film når søkeren er oppe.
Fotografier må framkalles i fotolaben før de kan undersøkes.
Lyd, musefølsomhet og fullskjerm finnes under SETTINGS.
Fullskjerm bruker skjermens native oppløsning; vindusstørrelsen huskes.

KREDITERING OG LISENSER
Se THIRD_PARTY_NOTICES.md og VT323-OFL.txt i denne mappen.
"""


def describe_tree(root):
    files, directories = [], []
    for path in [root, *regular_tree(root)]:
        relative = path.relative_to(root).as_posix()
        mode = format(stat.S_IMODE(path.stat().st_mode), "04o")
        if path.is_dir():
            directories.append({"path": relative, "mode": mode})
        elif relative != PACKAGE_MANIFEST:
            files.append({"path": relative, "bytes": path.stat().st_size, "mode": mode, "sha256": file_hash(path)})
    return files, directories


def make_package_manifest(stage, package_id, build):
    files, directories = describe_tree(stage)
    return {
        "schema": "signal47-chapter09-package-v1",
        "package_id": package_id,
        "base_revision": build["base_revision"],
        "unity_source_sha256": build["unity_source_sha256"],
        "build_payload_sha256": build["build_payload_sha256"],
        "player_sha256": build["player_sha256"],
        "package_payload_sha256": tree_hash((stage / item["path"] for item in files), stage),
        "package_hash_method": "Sorted relative file paths, NUL, file bytes; includes build metadata and package additions; excludes package-manifest.json itself. File modes and directories are recorded separately below.",
        "files": files,
        "directories": directories,
    }


def same_tree(left, right):
    require(describe_tree(left) == describe_tree(right), f"Existing immutable package differs: {right}")
    require((left / PACKAGE_MANIFEST).read_bytes() == (right / PACKAGE_MANIFEST).read_bytes(),
            f"Existing package manifest differs: {right}")
    require(stat.S_IMODE((left / PACKAGE_MANIFEST).stat().st_mode) == stat.S_IMODE((right / PACKAGE_MANIFEST).stat().st_mode),
            f"Existing package manifest permissions differ: {right}")


def write_archive(package, archive):
    # Stable metadata makes reruns byte-identical; stored permission bits are preserved.
    with archive.open("wb") as raw, gzip.GzipFile(filename="", fileobj=raw, mode="wb", mtime=0) as compressed:
        with tarfile.open(fileobj=compressed, mode="w", format=tarfile.PAX_FORMAT) as tar:
            for path in [package, *regular_tree(package)]:
                name = package.name if path == package else f"{package.name}/{path.relative_to(package).as_posix()}"
                info = tar.gettarinfo(str(path), arcname=name)
                info.uid = info.gid = 0
                info.uname = info.gname = ""
                info.mtime = 0
                info.pax_headers = {}
                if path.is_file():
                    with path.open("rb") as stream:
                        tar.addfile(info, stream)
                else:
                    tar.addfile(info)


def install_exact_file(path, contents, mode=0o644):
    if path.exists():
        require(path.is_file() and not path.is_symlink(), f"Refusing non-regular output: {path}")
        require(path.read_bytes() == contents and stat.S_IMODE(path.stat().st_mode) == mode,
                f"Existing immutable output differs: {path}")
        return
    # Exclusive creation refuses a competing run instead of replacing its result.
    with path.open("xb") as stream:
        stream.write(contents)
    path.chmod(mode)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dir", type=Path, default=ROOT / "Artifacts/GauntletLinux")
    parser.add_argument("--expect-source", help="Require this exact tested Unity source SHA-256.")
    parser.add_argument("--label", default="Chapter09", choices=["Chapter09", "Visual10", "NightSky12", "Menu14", "Recovery15", "Archive16", "Workstation18", "Resources19"], help="Identified release family; prior packages are retained.")
    parser.add_argument("--candidate", action="store_true", help="Label the package as awaiting gameplay/performance verification and preserve the default launcher.")
    parser.add_argument("--check-only", action="store_true", help="Read-only build/source verification; create no package or launcher.")
    args = parser.parse_args()
    require(args.label != "Archive16" or args.candidate, "Archive16 is a standalone study; --candidate is required to preserve the default game.")
    build_dir = args.build_dir.resolve()
    build = verify_build(ROOT, build_dir, args.expect_source)
    package_id = args.label + "-" + build["unity_source_sha256"][:12]
    releases = ROOT / "Artifacts/Releases"
    destination = releases / package_id
    archive = releases / f"SIGNAL47-{package_id}-Linux.tar.gz"
    if args.check_only:
        print(json.dumps({"verified": True, "package_id": package_id, "unity_source_sha256": build["unity_source_sha256"],
                          "build_payload_sha256": build["build_payload_sha256"], "planned_directory": str(destination)}, indent=2))
        return
    root_launcher = ROOT / "Spill-SIGNAL47.sh"
    if not args.candidate and (root_launcher.exists() or root_launcher.is_symlink()):
        require(root_launcher.is_file() and not root_launcher.is_symlink(), "Refusing non-regular repository launcher.")
        require(GENERATED_MARKER in root_launcher.read_text(encoding="utf-8"),
                "Spill-SIGNAL47.sh was not generated by this script; preserve and review it before replacing it.")
    releases.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".chapter09-package-", dir=releases) as temporary:
        workspace = Path(temporary)
        stage = workspace / package_id
        shutil.copytree(build_dir, stage, copy_function=shutil.copy2)
        stage.chmod(0o755)
        require(build_payload_hash(stage) == build["build_payload_sha256"], "Build changed during copying; nothing installed.")
        require(json.loads((stage / "build-manifest.json").read_text(encoding="utf-8")) == build,
                "Build manifest changed during copying.")
        state = "working-tree" if build["working_tree_changes"] else "clean"
        require((stage / "build-id.txt").read_text(encoding="utf-8").strip() ==
                f"{build['base_revision']} {state} source-sha256:{build['unity_source_sha256']}",
                "Build identity changed during copying.")
        for name, content, mode in (("START_HER.txt", start_text(package_id, build, args.candidate), 0o644),
                                    ("Start-SIGNAL47.sh", package_launcher(), 0o755)):
            require(not (stage / name).exists(), f"Build already contains reserved package file: {name}")
            (stage / name).write_text(content, encoding="utf-8")
            (stage / name).chmod(mode)
        require(not (stage / PACKAGE_MANIFEST).exists(), "Build already contains a package manifest.")
        package_manifest = make_package_manifest(stage, package_id, build)
        (stage / PACKAGE_MANIFEST).write_text(json.dumps(package_manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        (stage / PACKAGE_MANIFEST).chmod(0o644)
        require(source_hash(ROOT) == build["unity_source_sha256"], "Unity source changed while preparing package; nothing installed.")
        require(build_payload_hash(build_dir) == build["build_payload_sha256"], "Build payload changed while preparing package.")
        staged_archive = workspace / archive.name
        write_archive(stage, staged_archive)
        archive_digest = file_hash(staged_archive)
        if destination.exists() or destination.is_symlink():
            same_tree(stage, destination)
        if archive.exists() or archive.is_symlink():
            require(archive.is_file() and not archive.is_symlink() and file_hash(archive) == archive_digest,
                    f"Existing immutable archive differs: {archive}")
        sidecar = archive.with_name(archive.name + ".sha256")
        checksum = f"{archive_digest}  {archive.name}\n".encode("ascii")
        if sidecar.exists() or sidecar.is_symlink():
            require(sidecar.is_file() and not sidecar.is_symlink() and sidecar.read_bytes() == checksum,
                    f"Existing archive checksum differs: {sidecar}")
        # Only exact, fully checked outputs may be installed. Existing releases stay put.
        if not destination.exists():
            stage.rename(destination)
        if not archive.exists():
            staged_archive.chmod(0o644)
            staged_archive.rename(archive)
        install_exact_file(sidecar, checksum)
        if not args.candidate:
            launcher_temp = workspace / "Spill-SIGNAL47.sh"
            launcher_temp.write_text(repository_launcher(package_id), encoding="utf-8")
            launcher_temp.chmod(0o755)
            os.replace(launcher_temp, root_launcher)
    print(json.dumps({"package_id": package_id, "directory": str(destination), "archive": str(archive),
                      "archive_sha256": archive_digest, "package_payload_sha256": package_manifest["package_payload_sha256"],
                      "launcher": str(destination / "Start-SIGNAL47.sh") if args.candidate else str(root_launcher),
                      "candidate": args.candidate}, indent=2))


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"PACKAGING REFUSED: {error}", file=sys.stderr)
        sys.exit(1)
